// cards.js — Speculative Technologies card data

export const sharedFuturesExport = [
  'Near Future (2040s–2060s)',
  'Late 21st Century',
  '22nd Century',
  'After the Decoupling',
  'After the Planetary Stack',
  'A Future of Multiple Modernities',
  'Post-Anthropocene',
  'After the Collapse of Western Universalism',
  'Post-Singularity',
  'A Gravity-Free Future',
  'A Non-Physical Future',
  'An Archival Future',
  'An Abundant Future',
  'A Strength-Based Future',
  'A Religious Future',
  'A Deathless Future',
]

export const arcsByCulture = {
  Eastern: [
    'Era of the Sage-Kings (Fu Xi, Nüwa, Shennong) — Mythological Prehistory',
    'Shang Dynasty (1766–1122 BC)',
    'Zhou Dynasty (1122–256 BC)',
    'Han Dynasty (206 BC–220 CE)',
    'Six Dynasties (220–589)',
    'Tang Dynasty (618–907)',
    'Song Dynasty (960–1279)',
    'Yuan Dynasty (1271–1368)',
    'Ming Dynasty (1368–1644)',
    'Qing Dynasty (1644–1912)',
    'After the Opium Wars (1842–)',
    'Meiji Restoration Era (1868–)',
    'Early Republic of China (1912–1949)',
    'Cultural Revolution (1966–1976)',
    'Deng Xiaoping Reforms (1978–)',
    'Age of Platform Capital in China (2010–)',
    'DeepSeek Moment (2025)',
    'Sinofuturist Near Future',
    ...sharedFuturesExport,
  ],
  Western: [
    'Mythological Antiquity — Before Writing',
    'Classical Antiquity (600–300 BC)',
    'Roman Empire (27 BC–476 CE)',
    'Medieval Europe (500–1400)',
    'Renaissance (1400–1600)',
    'Scientific Revolution (1543–1687)',
    'Enlightenment (1685–1815)',
    'Industrial Revolution (1760–1840)',
    'Age of Empire (1870–1914)',
    'Interwar Period (1918–1939)',
    'Cold War (1947–1991)',
    'Soviet Cybernetics Era (1950s–1970s)',
    "Allende's Chile (1970–1973)",
    'Late 20th Century Globalization',
    'Age of Platform Capital (2010–)',
    ...sharedFuturesExport,
  ],
  Planetary: [
    'Jurassic',
    '4th century BC',
    '2nd century AD',
    '9th century',
    '13th century',
    '15th century',
    '17th century',
    '19th century',
    'early 20th century',
    'mid-20th century',
    'late 20th century',
    'early 21st century',
    ...sharedFuturesExport,
  ],
}

export const cards = {
  culture: {
    label: 'Culture',
    glyph: '◉',
    description: 'A cultural or civilizational context',
    items: ['Western', 'Eastern', 'Planetary'],
  },
  arc: {
    label: 'Arc',
    glyph: '◈',
    description: 'A historical era or temporal condition',
    items: [],
  },
  terrain: {
    label: 'Terrain',
    glyph: '◫',
    description: 'A domain of social or material life',
    items: [
      'governance', 'surveillance', 'infrastructure', 'logistics',
      'coordination', 'planning', 'military strategy', 'education',
      'memory', 'translation', 'ritual', 'cosmology', 'philosophy',
      'writing', 'archive', 'health', 'hygiene', 'labor', 'craft',
      'the body', 'movement', 'sensation', 'agriculture', 'energy',
      'the home', 'the city', 'ecology', 'trade', 'production',
      'communication', 'computation', 'measurement', 'navigation',
      'automation', 'media', 'data',
      'religion', 'moonlight', 'school', 'politics', 'pets',
      'entertainment', 'crystal', 'ice', 'shrines', 'law',
      'transportation', 'food', 'hierarchy', 'literature', 'citizenship',
      'AI', 'flowers', 'gender', 'music', 'family', 'ocean',
    ],
  },
  object: {
    label: 'Object',
    glyph: '◻',
    description: 'A class of technology or artifact',
    items: [
      'a clock', 'a compass', 'a map', 'a printing press', 'a loom',
      'a calendar', 'a measuring instrument', 'a mirror', 'a vessel',
      'a mechanism', 'a record', 'an interface', 'a network', 'a database',
      'a protocol', 'a signal', 'a code', 'a script', 'an index',
      'a garment', 'a tool', 'a prosthetic', 'a threshold', 'a container',
      'a surface', 'a feedback loop', 'a model', 'a simulation', 'a standard',
      'a diagram', 'a curriculum', 'a test', 'a classification', 'a score',
      'a machine', 'a sensor', 'a filter', 'a barrier', 'a channel', 'a platform',
      'a flute', 'a donut', 'a phone', 'a suitcase', 'a wearable',
      'a key', 'a puppy', 'a pearl', 'a bracelet', 'a gender identity',
      'a romantic relationship', 'a song', 'a food dish',
    ],
  },
}
